# Initial notebook to understand and visualize the data

In [ ]:
from dotenv import load_dotenv
from kaggle.api.kaggle_api_extended import KaggleApi
import os.path

load_dotenv()

api = KaggleApi()
api.authenticate()

dataset_slug = 'algozee/smartphone-usage-and-addiction-analysis-dataset'

fileAlreadyExists = os.path.isfile("data/Smartphone_Usage_And_Addiction_Analysis_7500_Rows.csv")

if fileAlreadyExists:
    print("Data already fetched")
else:
    print(f"Downloading {dataset_slug}...")
    api.dataset_download_files(dataset_slug, path='data/', unzip=True)
    print("Files downloaded and ready to use")

Downloading algozee/smartphone-usage-and-addiction-analysis-dataset...
Dataset URL: https://www.kaggle.com/datasets/algozee/smartphone-usage-and-addiction-analysis-dataset
Files downloaded and ready to use

## Initial data lookup

In [2]:
import pandas as pd
from IPython.display import display

data = pd.read_csv("data/Smartphone_Usage_And_Addiction_Analysis_7500_Rows.csv")

display(data.head())

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [8]:
data.describe()

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addicted_label
count,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000
mean,26.568800,7.499912,3.273484,2.014183,3.242420,6.737561,134.257333,97.832400,9.243827,0.707733
std,5.197108,2.609188,1.585342,1.146039,1.600765,1.283605,66.586883,48.423349,2.718281,0.454835
min,18.000000,3.000000,0.500000,0.000000,0.500000,4.500000,20.000000,15.000000,3.580000,0.000000
25%,22.000000,5.220000,1.910000,1.020000,1.850000,5.630000,76.000000,55.000000,6.960000,0.000000
50%,27.000000,7.525000,3.270000,2.040000,3.230000,6.720000,134.000000,98.000000,9.260000,1.000000
75%,31.000000,9.810000,4.630000,2.990000,4.640000,7.840000,191.000000,140.000000,11.540000,1.000000
max,35.000000,12.000000,6.000000,4.000000,6.000000,9.000000,250.000000,180.000000,14.880000,1.000000

In [7]:
data.isna().sum()

transaction_id               0
user_id                      0
age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            819
addicted_label               0
dtype: int64

In [9]:
print(data["addiction_level"].unique())

<StringArray>
[nan, 'Mild', 'Moderate', 'Severe']
Length: 4, dtype: str

### Investigating, why addiction level feature has missing values

In [12]:
missing = data[data["addiction_level"].isnull()].copy()
not_missing = data[data["addiction_level"].notnull()].copy()

print("Mean values for not missing data:")
print(not_missing.mean(numeric_only=True))

print("\nMean values for missing values in the addiciton level column:")
print(missing.mean(numeric_only=True))

Mean values for not missing data:
age                         26.580602
daily_screen_time_hours      7.864862
social_media_hours           3.400090
gaming_hours                 2.015176
work_study_hours             3.240322
sleep_hours                  6.744914
notifications_per_day      134.244275
app_opens_per_day           97.921269
weekend_screen_time          9.613552
addicted_label               0.794492
dtype: float64

Mean values for missing values in the addiciton level column:
age                         26.472527
daily_screen_time_hours      4.522833
social_media_hours           2.240696
gaming_hours                 2.006081
work_study_hours             3.259536
sleep_hours                  6.677582
notifications_per_day      134.363858
app_opens_per_day           97.107448
weekend_screen_time          6.227790
addicted_label               0.000000
dtype: float64

In [13]:
display(missing.head(30))

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
8,TXN00009,U00009,21,Other,4.38,1.38,2.72,3.78,6.23,172,134,6.20,High,Yes,NaN,0
11,TXN00012,U00012,27,Other,5.16,1.82,2.27,0.93,7.79,228,32,8.10,High,Yes,NaN,0
13,TXN00014,U00014,32,Male,4.09,1.74,1.35,3.74,5.54,76,16,4.77,High,Yes,NaN,0
15,TXN00016,U00016,21,Male,3.87,2.87,1.69,3.07,7.78,192,180,4.62,Medium,No,NaN,0
16,TXN00017,U00017,24,Other,4.71,2.97,1.69,2.03,5.62,39,128,7.23,High,Yes,NaN,0
21,TXN00022,U00022,34,Female,5.85,1.93,2.68,2.23,5.70,53,180,7.10,Medium,Yes,NaN,0
26,TXN00027,U00027,35,Female,4.33,1.20,1.23,5.44,8.08,240,25,7.08,Low,Yes,NaN,0
34,TXN00035,U00035,18,Other,5.73,1.66,3.14,3.84,5.95,133,128,7.92,High,No,NaN,0
44,TXN00045,U00045,23,Female,3.45,2.59,0.85,2.30,7.93,117,86,5.83,Medium,No,NaN,0
46,TXN00047,U00047,22,Female,5.15,3.10,0.46,5.71,6.59,85,109,6.07,High,Yes,NaN,0
98,TXN00099,U00099,34,Other,4.94,2.81,1.36,2.54,7.75,218,160,6.93,Low,Yes,NaN,0
101,TXN00102,U00102,27,Female,5.95,0.54,2.99,1.47,6.21,200,73,7.70,High,No,NaN,0
108,TXN00109,U00109,24,Male,5.89,3.12,0.60,0.84,4.97,250,102,8.85,Low,Yes,NaN,0
120,TXN00121,U00121,25,Female,5.71,0.76,1.68,4.87,6.56,48,142,7.70,Low,Yes,NaN,0
131,TXN00132,U00132,32,Other,4.93,3.87,2.78,5.99,5.40,54,33,6.56,High,No,NaN,0
137,TXN00138,U00138,22,Other,4.54,3.93,3.61,2.36,8.66,30,22,5.24,High,No,NaN,0
147,TXN00148,U00148,29,Other,5.98,1.10,1.67,2.19,8.54,243,176,6.55,Medium,No,NaN,0
169,TXN00170,U00170,24,Male,3.61,3.77,1.79,4.20,8.42,82,26,5.12,Low,Yes,NaN,0
177,TXN00178,U00178,29,Male,5.82,0.75,3.46,4.58,4.57,161,164,7.77,Medium,No,NaN,0
194,TXN00195,U00195,22,Female,5.70,3.82,2.78,3.13,5.30,121,96,6.93,High,No,NaN,0
199,TXN00200,U00200,21,Female,3.09,1.92,2.04,3.35,7.11,167,71,4.70,Medium,No,NaN,0
240,TXN00241,U00241,22,Male,3.82,1.87,1.42,3.32,7.55,86,59,4.40,Medium,No,NaN,0
254,TXN00255,U00255,22,Female,5.98,0.93,1.39,2.26,7.36,42,178,8.30,Medium,No,NaN,0
259,TXN00260,U00260,25,Male,3.86,2.66,2.20,3.20,4.75,20,124,4.58,High,No,NaN,0
265,TXN00266,U00266,20,Female,3.78,3.56,2.21,5.21,6.84,243,18,6.25,High,No,NaN,0
268,TXN00269,U00269,25,Male,3.44,3.11,1.07,2.55,6.02,223,92,4.72,Medium,Yes,NaN,0
271,TXN00272,U00272,19,Male,5.25,3.01,3.67,4.38,5.73,230,133,7.01,High,Yes,NaN,0
279,TXN00280,U00280,33,Other,4.15,1.92,3.23,4.70,5.32,194,100,6.29,Low,No,NaN,0

### It turns out, that the NaN value in addiction level feature probably just indicates that a person is not addicted, so I will just impute the NaN values with a string that is more informative

In [ ]:
data["addiction_level"] = data["addiction_level"].fillna("Not addicted")
data.isna().sum()

transaction_id             0
user_id                    0
age                        0
gender                     0
daily_screen_time_hours    0
social_media_hours         0
gaming_hours               0
work_study_hours           0
sleep_hours                0
notifications_per_day      0
app_opens_per_day          0
weekend_screen_time        0
stress_level               0
academic_work_impact       0
addiction_level            0
addicted_label             0
dtype: int64

In [17]:
data = data.drop(columns=["transaction_id", "user_id"])

## Saving the data for visualization

In [ ]:
data.to_csv("data/clean_data.csv")

## Creating additional dataframes for dashboard